# -*- coding: utf-8 -*-
"""Task2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tkiZ25NAPRQ7-3Zb4_eFHMpSGDG_tfC_
"""

# STEP 1: Install required libraries
!pip install -q diffusers transformers accelerate torch safetensors

# STEP 2: Import necessary packages
from diffusers import StableDiffusionPipeline
import torch
from PIL import Image
import os

# STEP 3: Load Stable Diffusion model (public, no auth token needed)
pipe = StableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

# STEP 4: Move model to appropriate device (GPU if available)
device = "cuda" if torch.cuda.is_available() else "cpu"
pipe = pipe.to(device)

# STEP 5: Define your text prompt
prompt = "A majestic dragon flying over a medieval castle at sunset"

# STEP 6: Generate image
image = pipe(prompt).images[0]

# STEP 7: Display the image in notebook
image.show()

# STEP 8: Save the image to file
output_path = "/content/generated_image.png"
image.save(output_path)
print(f"Image saved to {output_path}")

from google.colab import files
files.download("/content/generated_image.png")